version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/project/
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project/
          paths:
            - ./
  uxpin-code-cli:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/project/packages/uxpin-code-cli
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: uxpin-code-cli-dependencies-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: uxpin-code-cli-dependencies-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: make build
      - run:
          name: check
          command: make check
      - run:
          name: test-resources
          command: make test-resources
      - run:
          name: test
          command: ./node_modules/.bin/jest --testResultsProcessor="jest-junit-reporter" --coverage
          environment:
            TEST_REPORT_PATH: ./reports
      - store_test_results:
          path: ./reports
      - run:
          name: code-coverage
          command: ./packages/uxpin-code-cli/node_modules/.bin/codecov -F unittests uxpin-code-cli
          working_directory: ~/project/

workflows:
  version: 2
  build_and_test_packages:
    jobs:
      - build
      - uxpin-code-cli:
          requires:
            - build